spring:
  datasource:
    url: "jdbc:postgresql://192.168.31.169:5432/train"
    username: train_admin
    password: training
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    suffix: .html
    cache: false


mybatis:
  mapper-locations: classpath*:/mapper/*.xml # classpath in target folder
  type-aliases-package: train.model # important, affects .xml files
  configuration:
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true


logging:
  level:
    train.mapper: DEBUG


server:
  port: 8080